/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JMenuItem;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author David
 */
public class frmConsultaE extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmConsultaP
     */
    public frmConsultaE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboxTipoUsusario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsuario = new javax.swing.JTable();
        txtBuscarID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btmBuscar = new javax.swing.JButton();
        btmSalir = new javax.swing.JButton();
        btmBuscar2 = new javax.swing.JButton();
        btmGenerarPDF = new javax.swing.JToggleButton();
        btmImprimir = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opcActualizar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        opcExportar = new javax.swing.JMenuItem();
        opcImportar = new javax.swing.JMenuItem();

        setClosable(true);
        setTitle("Consultar Especimenes");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cplant16.png"))); // NOI18N

        cboxTipoUsusario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Planta", "Animal" }));
        cboxTipoUsusario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTipoUsusarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de Especimen");

        tableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Genero", "Tipo Usuario", "Codigo Colector"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableUsuario);

        jLabel3.setText("Buscar ID");

        btmBuscar.setText("Buscar");

        btmSalir.setText("Salir");

        btmBuscar2.setText("Buscar");

        btmGenerarPDF.setText("Generar PDF");

        btmImprimir.setText("Imprimir");

        jMenu1.setText("File");

        opcActualizar.setText("Actualizar");
        jMenu1.add(opcActualizar);
        jMenu1.add(jSeparator1);

        opcExportar.setText("Exportar .csv");
        jMenu1.add(opcExportar);

        opcImportar.setText("Importar .csv");
        jMenu1.add(opcImportar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btmImprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmGenerarPDF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmSalir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cboxTipoUsusario, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btmBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btmBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxTipoUsusario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btmBuscar)
                    .addComponent(btmBuscar2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmSalir)
                    .addComponent(btmGenerarPDF)
                    .addComponent(btmImprimir))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxTipoUsusarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTipoUsusarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxTipoUsusarioActionPerformed

    public JButton getBtmBuscar() {
        return btmBuscar;
    }

    public void setBtmBuscar(JButton btmBuscar) {
        this.btmBuscar = btmBuscar;
    }

    public JButton getBtmSalir() {
        return btmSalir;
    }

    public void setBtmSalir(JButton btmSalir) {
        this.btmSalir = btmSalir;
    }

    public JComboBox<String> getCboxTipoUsusario() {
        return cboxTipoUsusario;
    }

    public void setCboxTipoUsusario(JComboBox<String> cboxTipoUsusario) {
        this.cboxTipoUsusario = cboxTipoUsusario;
    }

    public JMenuItem getOpcActualizar() {
        return opcActualizar;
    }

    public void setOpcActualizar(JMenuItem opcActualizar) {
        this.opcActualizar = opcActualizar;
    }

    public JMenuItem getOpcExportar() {
        return opcExportar;
    }

    public void setOpcExportar(JMenuItem opcExportar) {
        this.opcExportar = opcExportar;
    }

    public JMenuItem getOpcImportar() {
        return opcImportar;
    }

    public void setOpcImportar(JMenuItem opcImportar) {
        this.opcImportar = opcImportar;
    }

    public JTable getTableUsuario() {
        return tableUsuario;
    }

    public void setTableUsuario(JTable tableUsuario) {
        this.tableUsuario = tableUsuario;
    }

    public JTextField getTxtBuscarID() {
        return txtBuscarID;
    }

    public void setTxtBuscarID(JTextField txtBuscarID) {
        this.txtBuscarID = txtBuscarID;
    }

    public JButton getBtmBuscar2() {
        return btmBuscar2;
    }

    public void setBtmBuscar2(JButton btmBuscar2) {
        this.btmBuscar2 = btmBuscar2;
    }

    public JToggleButton getBtmGenerarPDF() {
        return btmGenerarPDF;
    }

    public void setBtmGenerarPDF(JToggleButton btmGenerarPDF) {
        this.btmGenerarPDF = btmGenerarPDF;
    }

    public JToggleButton getBtmImprimir() {
        return btmImprimir;
    }

    public void setBtmImprimir(JToggleButton btmImprimir) {
        this.btmImprimir = btmImprimir;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmBuscar;
    private javax.swing.JButton btmBuscar2;
    private javax.swing.JToggleButton btmGenerarPDF;
    private javax.swing.JToggleButton btmImprimir;
    private javax.swing.JButton btmSalir;
    private javax.swing.JComboBox<String> cboxTipoUsusario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem opcActualizar;
    private javax.swing.JMenuItem opcExportar;
    private javax.swing.JMenuItem opcImportar;
    private javax.swing.JTable tableUsuario;
    private javax.swing.JTextField txtBuscarID;
    // End of variables declaration//GEN-END:variables
}
