/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author David
 */
public class frmEspecimen extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmEspecimen
     */
    public frmEspecimen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEspecimenID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jcomboColector = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEspecie = new javax.swing.JTextField();
        jpanelAnimal = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jcomboPelaje = new javax.swing.JComboBox<>();
        jcomboExtre = new javax.swing.JComboBox<>();
        jpanelPlantas = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jcomboFrutos = new javax.swing.JComboBox<>();
        jcomboHojas = new javax.swing.JComboBox<>();
        btmCancelar = new javax.swing.JButton();
        btmRegistrar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jcomboEspecimen = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jDateColeccion = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtOrden = new javax.swing.JTextField();
        txtFamilia = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Registro Especimen");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plant16.png"))); // NOI18N

        jLabel1.setText("Especimen ID");

        txtEspecimenID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecimenIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Colector ID");

        jLabel3.setText("Fecha Colección");

        jLabel4.setText("Orden");

        jLabel5.setText("Familia");

        jLabel6.setText("Genero");

        jLabel7.setText("Especie");

        jLabel8.setText("Pelaje");

        jLabel9.setText("Extremidades");

        jcomboPelaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plumas", "Pelos", "Escamas", "Liso" }));

        jcomboExtre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "2", "4", "6", "8" }));

        javax.swing.GroupLayout jpanelAnimalLayout = new javax.swing.GroupLayout(jpanelAnimal);
        jpanelAnimal.setLayout(jpanelAnimalLayout);
        jpanelAnimalLayout.setHorizontalGroup(
            jpanelAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelAnimalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanelAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcomboPelaje, 0, 105, Short.MAX_VALUE)
                    .addComponent(jcomboExtre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(185, 185, 185))
        );
        jpanelAnimalLayout.setVerticalGroup(
            jpanelAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelAnimalLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jpanelAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcomboPelaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jcomboExtre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel10.setText("Frutos");

        jLabel11.setText("Hojas");

        jcomboFrutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monocarpelar", "Policarpelar" }));
        jcomboFrutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboFrutosActionPerformed(evt);
            }
        });

        jcomboHojas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Compuesta", "Simple" }));

        javax.swing.GroupLayout jpanelPlantasLayout = new javax.swing.GroupLayout(jpanelPlantas);
        jpanelPlantas.setLayout(jpanelPlantasLayout);
        jpanelPlantasLayout.setHorizontalGroup(
            jpanelPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelPlantasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jpanelPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcomboHojas, 0, 110, Short.MAX_VALUE)
                    .addComponent(jcomboFrutos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpanelPlantasLayout.setVerticalGroup(
            jpanelPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelPlantasLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jpanelPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jcomboFrutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelPlantasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jcomboHojas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btmCancelar.setText("Cancelar");

        btmRegistrar.setText("Registrar");

        jLabel12.setText("Tipo de Especimen");

        jcomboEspecimen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Planta", "Animal" }));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Datos Generales");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Datos Especie");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Datos de tipo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpanelAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpanelPlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btmRegistrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btmCancelar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13))
                                        .addGap(51, 51, 51))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEspecimenID)
                                    .addComponent(jcomboColector, 0, 265, Short.MAX_VALUE)
                                    .addComponent(jcomboEspecimen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateColeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(112, 112, 112)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEspecie, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                    .addComponent(txtOrden)
                                    .addComponent(txtFamilia)
                                    .addComponent(txtGenero)))
                            .addComponent(jLabel14))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jcomboEspecimen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEspecimenID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcomboColector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addComponent(jDateColeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpanelPlantas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpanelAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 27, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmCancelar)
                    .addComponent(btmRegistrar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEspecimenIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecimenIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecimenIDActionPerformed

    private void jcomboFrutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboFrutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboFrutosActionPerformed

    public JButton getBtmCancelar() {
        return btmCancelar;
    }

    public void setBtmCancelar(JButton btmCancelar) {
        this.btmCancelar = btmCancelar;
    }

    public JButton getBtmRegistrar() {
        return btmRegistrar;
    }

    public void setBtmRegistrar(JButton btmRegistrar) {
        this.btmRegistrar = btmRegistrar;
    }

    public JDateChooser getjDateColeccion() {
        return jDateColeccion;
    }

    public void setjDateColeccion(JDateChooser jDateColeccion) {
        this.jDateColeccion = jDateColeccion;
    }

    public JComboBox<String> getJcomboColector() {
        return jcomboColector;
    }

    public void setJcomboColector(JComboBox<String> jcomboColector) {
        this.jcomboColector = jcomboColector;
    }

    public JComboBox<String> getJcomboEspecimen() {
        return jcomboEspecimen;
    }

    public void setJcomboEspecimen(JComboBox<String> jcomboEspecimen) {
        this.jcomboEspecimen = jcomboEspecimen;
    }

    public JComboBox<String> getJcomboExtre() {
        return jcomboExtre;
    }

    public void setJcomboExtre(JComboBox<String> jcomboExtre) {
        this.jcomboExtre = jcomboExtre;
    }

    public JComboBox<String> getJcomboFrutos() {
        return jcomboFrutos;
    }

    public void setJcomboFrutos(JComboBox<String> jcomboFrutos) {
        this.jcomboFrutos = jcomboFrutos;
    }

    public JComboBox<String> getJcomboHojas() {
        return jcomboHojas;
    }

    public void setJcomboHojas(JComboBox<String> jcomboHojas) {
        this.jcomboHojas = jcomboHojas;
    }

    public JComboBox<String> getJcomboPelaje() {
        return jcomboPelaje;
    }

    public void setJcomboPelaje(JComboBox<String> jcomboPelaje) {
        this.jcomboPelaje = jcomboPelaje;
    }

    public JPanel getJpanelAnimal() {
        return jpanelAnimal;
    }

    public void setJpanelAnimal(JPanel jpanelAnimal) {
        this.jpanelAnimal = jpanelAnimal;
    }

    public JPanel getJpanelPlantas() {
        return jpanelPlantas;
    }

    public void setJpanelPlantas(JPanel jpanelPlantas) {
        this.jpanelPlantas = jpanelPlantas;
    }

    public JTextField getTxtEspecie() {
        return txtEspecie;
    }

    public void setTxtEspecie(JTextField txtEspecie) {
        this.txtEspecie = txtEspecie;
    }

    public JTextField getTxtEspecimenID() {
        return txtEspecimenID;
    }

    public void setTxtEspecimenID(JTextField txtEspecimenID) {
        this.txtEspecimenID = txtEspecimenID;
    }

    public JTextField getTxtFamilia() {
        return txtFamilia;
    }

    public void setTxtFamilia(JTextField txtFamilia) {
        this.txtFamilia = txtFamilia;
    }

    public JTextField getTxtGenero() {
        return txtGenero;
    }

    public void setTxtGenero(JTextField txtGenero) {
        this.txtGenero = txtGenero;
    }

    public JTextField getTxtOrden() {
        return txtOrden;
    }

    public void setTxtOrden(JTextField txtOrden) {
        this.txtOrden = txtOrden;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmCancelar;
    private javax.swing.JButton btmRegistrar;
    private com.toedter.calendar.JDateChooser jDateColeccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jcomboColector;
    private javax.swing.JComboBox<String> jcomboEspecimen;
    private javax.swing.JComboBox<String> jcomboExtre;
    private javax.swing.JComboBox<String> jcomboFrutos;
    private javax.swing.JComboBox<String> jcomboHojas;
    private javax.swing.JComboBox<String> jcomboPelaje;
    private javax.swing.JPanel jpanelAnimal;
    private javax.swing.JPanel jpanelPlantas;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtEspecimenID;
    private javax.swing.JTextField txtFamilia;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtOrden;
    // End of variables declaration//GEN-END:variables
}
