/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JToolBar;

/**
 *
 * @author David
 */
public class frmInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jToolBar3 = new javax.swing.JToolBar();
        btmLogin = new javax.swing.JButton();
        btmCrearEsp = new javax.swing.JButton();
        btmConsultarEsp = new javax.swing.JButton();
        btmSalida2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opcConect = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        opcSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opcCrearUsuario = new javax.swing.JMenuItem();
        opcConsultarUsuario = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        opcCrearEsp = new javax.swing.JMenuItem();
        opcConsultarEsp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        jToolBar3.setFloatable(true);
        jToolBar3.setRollover(true);

        btmLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user32.png"))); // NOI18N
        btmLogin.setFocusable(false);
        btmLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btmLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btmLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmLoginActionPerformed(evt);
            }
        });
        jToolBar3.add(btmLogin);

        btmCrearEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plant32.png"))); // NOI18N
        btmCrearEsp.setFocusable(false);
        btmCrearEsp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btmCrearEsp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(btmCrearEsp);

        btmConsultarEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cplant32.png"))); // NOI18N
        btmConsultarEsp.setFocusable(false);
        btmConsultarEsp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btmConsultarEsp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btmConsultarEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmConsultarEspActionPerformed(evt);
            }
        });
        jToolBar3.add(btmConsultarEsp);

        btmSalida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit32.png"))); // NOI18N
        btmSalida2.setToolTipText("");
        btmSalida2.setFocusable(false);
        btmSalida2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btmSalida2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(btmSalida2);

        jMenu1.setText("Archivo");

        opcConect.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcConect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/conect16.png"))); // NOI18N
        opcConect.setText("Verificar Conexion");
        opcConect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcConectActionPerformed(evt);
            }
        });
        jMenu1.add(opcConect);
        jMenu1.add(jSeparator1);

        opcSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit16.png"))); // NOI18N
        opcSalir.setText("Salir");
        jMenu1.add(opcSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Datos");

        opcCrearUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user16.png"))); // NOI18N
        opcCrearUsuario.setText("Nuevo Usuario");
        jMenu2.add(opcCrearUsuario);

        opcConsultarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcConsultarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/network16.png"))); // NOI18N
        opcConsultarUsuario.setText("Consultar Usuario");
        opcConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcConsultarUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(opcConsultarUsuario);
        jMenu2.add(jSeparator3);

        opcCrearEsp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcCrearEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plant16.png"))); // NOI18N
        opcCrearEsp.setText("Nuevo Especimen");
        jMenu2.add(opcCrearEsp);

        opcConsultarEsp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opcConsultarEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cplant16.png"))); // NOI18N
        opcConsultarEsp.setText("Consultar Especimen");
        jMenu2.add(opcConsultarEsp);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
            .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmLoginActionPerformed

    private void btmConsultarEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmConsultarEspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmConsultarEspActionPerformed

    private void opcConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcConsultarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcConsultarUsuarioActionPerformed

    private void opcConectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcConectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcConectActionPerformed

    /**
     * @param args the command line arguments
     */

    public JButton getBtmConsultarEsp() {
        return btmConsultarEsp;
    }

    public void setBtmConsultarEsp(JButton btmConsultarEsp) {
        this.btmConsultarEsp = btmConsultarEsp;
    }

    public JButton getBtmCrearEsp() {
        return btmCrearEsp;
    }

    public void setBtmCrearEsp(JButton btmCrearEsp) {
        this.btmCrearEsp = btmCrearEsp;
    }

    public JButton getBtmLogin() {
        return btmLogin;
    }

    public void setBtmLogin(JButton btmLogin) {
        this.btmLogin = btmLogin;
    }

    public JButton getBtmSalida2() {
        return btmSalida2;
    }

    public void setBtmSalida2(JButton btmSalida2) {
        this.btmSalida2 = btmSalida2;
    }

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }

    public void setjMenu1(JMenu jMenu1) {
        this.jMenu1 = jMenu1;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public void setjMenu2(JMenu jMenu2) {
        this.jMenu2 = jMenu2;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JPopupMenu.Separator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JPopupMenu.Separator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JPopupMenu.Separator getjSeparator3() {
        return jSeparator3;
    }

    public void setjSeparator3(JPopupMenu.Separator jSeparator3) {
        this.jSeparator3 = jSeparator3;
    }


    public JToolBar getjToolBar3() {
        return jToolBar3;
    }

    public void setjToolBar3(JToolBar jToolBar3) {
        this.jToolBar3 = jToolBar3;
    }

    public JMenuItem getOpcConect() {
        return opcConect;
    }

    public void setOpcConect(JMenuItem opcConect) {
        this.opcConect = opcConect;
    }

    public JMenuItem getOpcConsultarEsp() {
        return opcConsultarEsp;
    }

    public void setOpcConsultarEsp(JMenuItem opcConsultarEsp) {
        this.opcConsultarEsp = opcConsultarEsp;
    }

    public JMenuItem getOpcConsultarUsuario() {
        return opcConsultarUsuario;
    }

    public void setOpcConsultarUsuario(JMenuItem opcConsultarUsuario) {
        this.opcConsultarUsuario = opcConsultarUsuario;
    }

    public JMenuItem getOpcCrearEsp() {
        return opcCrearEsp;
    }

    public void setOpcCrearEsp(JMenuItem opcCrearEsp) {
        this.opcCrearEsp = opcCrearEsp;
    }

    public JMenuItem getOpcCrearUsuario() {
        return opcCrearUsuario;
    }

    public void setOpcCrearUsuario(JMenuItem opcCrearUsuario) {
        this.opcCrearUsuario = opcCrearUsuario;
    }

    public JMenuItem getOpcSalir() {
        return opcSalir;
    }
    
    

    /**
     * @param args the command line arguments
     */
    public void setOpcSalir(JMenuItem opcSalir) {
        this.opcSalir = opcSalir;
    }

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmConsultarEsp;
    private javax.swing.JButton btmCrearEsp;
    private javax.swing.JButton btmLogin;
    private javax.swing.JButton btmSalida2;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JMenuItem opcConect;
    private javax.swing.JMenuItem opcConsultarEsp;
    private javax.swing.JMenuItem opcConsultarUsuario;
    private javax.swing.JMenuItem opcCrearEsp;
    private javax.swing.JMenuItem opcCrearUsuario;
    private javax.swing.JMenuItem opcSalir;
    // End of variables declaration//GEN-END:variables

}
