/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author David
 */
public class frmPersona extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmPersona
     */
    public frmPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpUserType = new javax.swing.ButtonGroup();
        btngrpGender = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        txtNombre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrimerApe = new javax.swing.JTextField();
        txtSegundoApe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        IblImg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbtmHom = new javax.swing.JRadioButton();
        rbtmMuj = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fotoUsuario = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jDateNacimiento = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        panelInvestigador = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtIdColector = new javax.swing.JTextField();
        checkAnimales = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        checkPlantas = new javax.swing.JCheckBox();
        txtCitacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        panelUsuario = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cboxUniversidades = new javax.swing.JComboBox<>();
        fotoUniversidad = new javax.swing.JLabel();
        cboxUserType = new javax.swing.JComboBox<>();
        btmRegistrar = new javax.swing.JButton();
        btmCancelar = new javax.swing.JButton();
        btmLimpiar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Registro Persona");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user16.png"))); // NOI18N

        jLabel1.setText("Primer Nombre");

        jLabel2.setText("Primer Apellido");

        txtSegundoApe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSegundoApeActionPerformed(evt);
            }
        });

        jLabel3.setText("Segundo Apellido");

        IblImg.setOpaque(true);

        jLabel4.setText("Genero:");

        rbtmHom.setText("Hombre");
        rbtmHom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtmHomActionPerformed(evt);
            }
        });

        rbtmMuj.setText("Mujer");

        jLabel5.setText("Fecha Nacimiento:");

        jLabel13.setText("Identificacion");

        jLabel15.setText("Fotografia");

        javax.swing.GroupLayout txtNombreLayout = new javax.swing.GroupLayout(txtNombre);
        txtNombre.setLayout(txtNombreLayout);
        txtNombreLayout.setHorizontalGroup(
            txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtNombreLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtmMuj)
                    .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(txtNombreLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(jDateNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtmHom)
                            .addComponent(jLabel4)
                            .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(txtNombreLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, txtNombreLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPrimerApe, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(txtNombreLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(txtNombreLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSegundoApe, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fotoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(34, 34, 34))
            .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(txtNombreLayout.createSequentialGroup()
                    .addGap(152, 152, 152)
                    .addComponent(IblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(355, Short.MAX_VALUE)))
        );
        txtNombreLayout.setVerticalGroup(
            txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtNombreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fotoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(txtNombreLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrimerApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSegundoApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtmHom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtmMuj)
                .addGap(12, 12, 12)
                .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jDateNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(txtNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(txtNombreLayout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(IblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(155, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Datos Personales", txtNombre);

        jLabel9.setText("Tipo de Usuario:");

        jLabel11.setText("ID Colector:");

        checkAnimales.setText("Animales");

        jLabel12.setText("Grupo de trabajo:");

        checkPlantas.setText("Plantas");

        jLabel14.setText("Citación:");

        javax.swing.GroupLayout panelInvestigadorLayout = new javax.swing.GroupLayout(panelInvestigador);
        panelInvestigador.setLayout(panelInvestigadorLayout);
        panelInvestigadorLayout.setHorizontalGroup(
            panelInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInvestigadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCitacion)
                    .addComponent(txtIdColector)
                    .addGroup(panelInvestigadorLayout.createSequentialGroup()
                        .addGroup(panelInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkPlantas)
                            .addComponent(checkAnimales))
                        .addGap(0, 75, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelInvestigadorLayout.setVerticalGroup(
            panelInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInvestigadorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtIdColector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkAnimales)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkPlantas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtCitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel10.setText("Institución a la que pertenece:");

        cboxUniversidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Universidad Distrital Francisco Jose de Caldas", "Universidad Nacional de Colombia", "Jardin Botánico", "Instituto Humbolt" }));
        cboxUniversidades.setToolTipText("");

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(cboxUniversidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxUniversidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        cboxUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrativo", "Investigador", "Visitante" }));
        cboxUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxUserTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(26, 26, 26)
                        .addComponent(cboxUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(fotoUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboxUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(fotoUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos Académicos", jPanel2);

        btmRegistrar.setText("Registrar");

        btmCancelar.setText("Cancelar");

        btmLimpiar.setText("Limpiar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btmLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btmRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btmCancelar)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmRegistrar)
                    .addComponent(btmCancelar)
                    .addComponent(btmLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtmHomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtmHomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtmHomActionPerformed

    private void txtSegundoApeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSegundoApeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSegundoApeActionPerformed

    private void cboxUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxUserTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxUserTypeActionPerformed

    public JLabel getIblImg() {
        return IblImg;
    }

    public void setIblImg(JLabel IblImg) {
        this.IblImg = IblImg;
    }

    public JButton getBtmCancelar() {
        return btmCancelar;
    }

    public void setBtmCancelar(JButton btmCancelar) {
        this.btmCancelar = btmCancelar;
    }

    public JButton getBtmRegistrar() {
        return btmRegistrar;
    }

    public void setBtmRegistrar(JButton btmRegistrar) {
        this.btmRegistrar = btmRegistrar;
    }

    public ButtonGroup getBtngrpGender() {
        return btngrpGender;
    }

    public void setBtngrpGender(ButtonGroup btngrpGender) {
        this.btngrpGender = btngrpGender;
    }

    public ButtonGroup getBtngrpUserType() {
        return btngrpUserType;
    }

    public void setBtngrpUserType(ButtonGroup btngrpUserType) {
        this.btngrpUserType = btngrpUserType;
    }

    public JCheckBox getCheckAnimales() {
        return checkAnimales;
    }

    public void setCheckAnimales(JCheckBox checkAnimales) {
        this.checkAnimales = checkAnimales;
    }

    public JCheckBox getCheckPlantas() {
        return checkPlantas;
    }

    public void setCheckPlantas(JCheckBox checkPlantas) {
        this.checkPlantas = checkPlantas;
    }

    public JLabel getFotoUniversidad() {
        return fotoUniversidad;
    }

    public void setFotoUniversidad(JLabel fotoUniversidad) {
        this.fotoUniversidad = fotoUniversidad;
    }

    public JLabel getFotoUsuario() {
        return fotoUsuario;
    }

    public void setFotoUsuario(JLabel fotoUsuario) {
        this.fotoUsuario = fotoUsuario;
    }

    public JDateChooser getjDateNacimiento() {
        return jDateNacimiento;
    }

    public void setjDateNacimiento(JDateChooser jDateNacimiento) {
        this.jDateNacimiento = jDateNacimiento;
    }

    public JPanel getPanelInvestigador() {
        return panelInvestigador;
    }

    public void setPanelInvestigador(JPanel panelInvestigador) {
        this.panelInvestigador = panelInvestigador;
    }

    public JPanel getPanelUsuario() {
        return panelUsuario;
    }

    public void setPanelUsuario(JPanel panelUsuario) {
        this.panelUsuario = panelUsuario;
    }

    public JRadioButton getRbtmHom() {
        return rbtmHom;
    }

    public void setRbtmHom(JRadioButton rbtmHom) {
        this.rbtmHom = rbtmHom;
    }

    public JRadioButton getRbtmMuj() {
        return rbtmMuj;
    }

    public void setRbtmMuj(JRadioButton rbtmMuj) {
        this.rbtmMuj = rbtmMuj;
    }

    public JTextField getTxtCitacion() {
        return txtCitacion;
    }

    public void setTxtCitacion(JTextField txtCitacion) {
        this.txtCitacion = txtCitacion;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(JTextField txtId) {
        this.txtId = txtId;
    }

    public JTextField getTxtIdColector() {
        return txtIdColector;
    }

    public void setTxtIdColector(JTextField txtIdColector) {
        this.txtIdColector = txtIdColector;
    }

    public JTextField getTxtNom() {
        return txtNom;
    }

    public void setTxtNom(JTextField txtNom) {
        this.txtNom = txtNom;
    }

    public JPanel getTxtNombre() {
        return txtNombre;
    }

    public void setTxtNombre(JPanel txtNombre) {
        this.txtNombre = txtNombre;
    }

    public JTextField getTxtPrimerApe() {
        return txtPrimerApe;
    }

    public void setTxtPrimerApe(JTextField txtPrimerApe) {
        this.txtPrimerApe = txtPrimerApe;
    }

    public JTextField getTxtSegundoApe() {
        return txtSegundoApe;
    }

    public void setTxtSegundoApe(JTextField txtSegundoApe) {
        this.txtSegundoApe = txtSegundoApe;
    }

    public JButton getBtmLimpiar() {
        return btmLimpiar;
    }

    public void setBtmLimpiar(JButton btmLimpiar) {
        this.btmLimpiar = btmLimpiar;
    }

    public JComboBox<String> getCboxUniversidades() {
        return cboxUniversidades;
    }

    public void setCboxUniversidades(JComboBox<String> cboxUniversidades) {
        this.cboxUniversidades = cboxUniversidades;
    }

    public JComboBox<String> getCboxUserType() {
        return cboxUserType;
    }

    public void setCboxUserType(JComboBox<String> cboxUserType) {
        this.cboxUserType = cboxUserType;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IblImg;
    private javax.swing.JButton btmCancelar;
    private javax.swing.JButton btmLimpiar;
    private javax.swing.JButton btmRegistrar;
    private javax.swing.ButtonGroup btngrpGender;
    private javax.swing.ButtonGroup btngrpUserType;
    private javax.swing.JComboBox<String> cboxUniversidades;
    private javax.swing.JComboBox<String> cboxUserType;
    private javax.swing.JCheckBox checkAnimales;
    private javax.swing.JCheckBox checkPlantas;
    private javax.swing.JLabel fotoUniversidad;
    private javax.swing.JLabel fotoUsuario;
    private com.toedter.calendar.JDateChooser jDateNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelInvestigador;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JRadioButton rbtmHom;
    private javax.swing.JRadioButton rbtmMuj;
    private javax.swing.JTextField txtCitacion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdColector;
    private javax.swing.JTextField txtNom;
    private javax.swing.JPanel txtNombre;
    private javax.swing.JTextField txtPrimerApe;
    private javax.swing.JTextField txtSegundoApe;
    // End of variables declaration//GEN-END:variables
}
