/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author David
 */
public class frmConsultaMDI extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmConsultaMDI
     */
    public frmConsultaMDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngVehiculo = new javax.swing.ButtonGroup();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculos = new javax.swing.JTable();
        txtTotal = new javax.swing.JTextField();
        RdboCarro = new javax.swing.JRadioButton();
        RdbMoto = new javax.swing.JRadioButton();
        RdbTodos = new javax.swing.JRadioButton();
        btmCerrar = new javax.swing.JButton();
        btmActualizar = new javax.swing.JToggleButton();

        setClosable(true);
        setTitle("Consultar Vehiculo");

        jLabel14.setText("Total");

        tblVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NmrFormulario", "Propietario", "Placa", "Marca", "Modelo", "Valor", "Impuesto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVehiculos);

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        RdboCarro.setText("Carro");

        RdbMoto.setText("Moto");
        RdbMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdbMotoActionPerformed(evt);
            }
        });

        RdbTodos.setText("Todos");
        RdbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdbTodosActionPerformed(evt);
            }
        });

        btmCerrar.setText("Cerrar");

        btmActualizar.setText("Actualizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(390, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(RdbTodos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdbMoto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RdboCarro))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btmActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btmCerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RdbMoto)
                    .addComponent(RdboCarro)
                    .addComponent(RdbTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmCerrar)
                    .addComponent(btmActualizar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void RdbMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdbMotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdbMotoActionPerformed

    private void RdbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdbTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RdbTodosActionPerformed

    public JRadioButton getRdbMoto() {
        return RdbMoto;
    }

    public void setRdbMoto(JRadioButton RdbMoto) {
        this.RdbMoto = RdbMoto;
    }

    public JRadioButton getRdbTodos() {
        return RdbTodos;
    }

    public void setRdbTodos(JRadioButton RdbTodos) {
        this.RdbTodos = RdbTodos;
    }

    public JRadioButton getRdboCarro() {
        return RdboCarro;
    }

    public void setRdboCarro(JRadioButton RdboCarro) {
        this.RdboCarro = RdboCarro;
    }

    public JButton getBtmCerrar() {
        return btmCerrar;
    }

    public void setBtmCerrar(JButton btmCerrar) {
        this.btmCerrar = btmCerrar;
    }

    public JLabel getjLabel14() {
        return jLabel14;
    }

    public void setjLabel14(JLabel jLabel14) {
        this.jLabel14 = jLabel14;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTblVehiculos() {
        return tblVehiculos;
    }

    public void setTblVehiculos(JTable tblVehiculos) {
        this.tblVehiculos = tblVehiculos;
    }

    public JTextField getTxtTotal() {
        return txtTotal;
    }

    public void setTxtTotal(JTextField txtTotal) {
        this.txtTotal = txtTotal;
    }

    public ButtonGroup getBtngVehiculo() {
        return btngVehiculo;
    }

    public void setBtngVehiculo(ButtonGroup btngVehiculo) {
        this.btngVehiculo = btngVehiculo;
    }

    public JToggleButton getBtmActualizar() {
        return btmActualizar;
    }

    public void setBtmActualizar(JToggleButton btmActualizar) {
        this.btmActualizar = btmActualizar;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RdbMoto;
    private javax.swing.JRadioButton RdbTodos;
    private javax.swing.JRadioButton RdboCarro;
    private javax.swing.JToggleButton btmActualizar;
    private javax.swing.JButton btmCerrar;
    private javax.swing.ButtonGroup btngVehiculo;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVehiculos;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
