/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JToolBar;

/**
 *
 * @author David
 */
public class frmInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        btmRegistrar = new javax.swing.JButton();
        btmConsultar = new javax.swing.JButton();
        btmSalir = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        ArchivoMenu = new javax.swing.JMenu();
        opcRegistrar = new javax.swing.JMenuItem();
        opcSalir = new javax.swing.JMenuItem();
        ConsultarMenu = new javax.swing.JMenu();
        opcConsultar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btmRegistrar.setText("Ingresar Vehiculo");
        btmRegistrar.setFocusable(false);
        btmRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btmRegistrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btmRegistrar);

        btmConsultar.setText("Consultar Vehiculo");
        btmConsultar.setFocusable(false);
        btmConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btmConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btmConsultar);

        btmSalir.setText("Salir");
        btmSalir.setFocusable(false);
        btmSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btmSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btmSalir);

        ArchivoMenu.setMnemonic('f');
        ArchivoMenu.setText("Archivo");

        opcRegistrar.setMnemonic('o');
        opcRegistrar.setText("Registrar");
        ArchivoMenu.add(opcRegistrar);

        opcSalir.setMnemonic('x');
        opcSalir.setText("Exit");
        opcSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSalirActionPerformed(evt);
            }
        });
        ArchivoMenu.add(opcSalir);

        menuBar.add(ArchivoMenu);

        ConsultarMenu.setText("Consultar");

        opcConsultar.setText("Lista Vehiculos");
        ConsultarMenu.add(opcConsultar);

        menuBar.add(ConsultarMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_opcSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    public JMenu getArchivoMenu() {
        return ArchivoMenu;
    }

    public void setArchivoMenu(JMenu ArchivoMenu) {
        this.ArchivoMenu = ArchivoMenu;
    }

    public JMenu getConsultarMenu() {
        return ConsultarMenu;
    }

    public void setConsultarMenu(JMenu ConsultarMenu) {
        this.ConsultarMenu = ConsultarMenu;
    }

    public JButton getBtmConsultar() {
        return btmConsultar;
    }

    public void setBtmConsultar(JButton btmConsultar) {
        this.btmConsultar = btmConsultar;
    }

    public JButton getBtmRegistrar() {
        return btmRegistrar;
    }

    public void setBtmRegistrar(JButton btmRegistrar) {
        this.btmRegistrar = btmRegistrar;
    }

    public JButton getBtmSalir() {
        return btmSalir;
    }

    public void setBtmSalir(JButton btmSalir) {
        this.btmSalir = btmSalir;
    }

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    public void setDesktopPane(JDesktopPane desktopPane) {
        this.desktopPane = desktopPane;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }

    
    public void setMenuBar(JMenuBar menuBar) {
        this.menuBar = menuBar;
    }

    public JMenuItem getOpcConsultar() {
        return opcConsultar;
    }

    public void setOpcConsultar(JMenuItem opcConsultar) {
        this.opcConsultar = opcConsultar;
    }

    public JMenuItem getOpcRegistrar() {
        return opcRegistrar;
    }

    public void setOpcRegistrar(JMenuItem opcRegistrar) {
        this.opcRegistrar = opcRegistrar;
    }

    public JMenuItem getOpcSalir() {
        return opcSalir;
    }

    /**
     * @param args the command line arguments
     */
    public void setOpcSalir(JMenuItem opcSalir) {
        this.opcSalir = opcSalir;
    }

    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ArchivoMenu;
    private javax.swing.JMenu ConsultarMenu;
    private javax.swing.JButton btmConsultar;
    private javax.swing.JButton btmRegistrar;
    private javax.swing.JButton btmSalir;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem opcConsultar;
    private javax.swing.JMenuItem opcRegistrar;
    private javax.swing.JMenuItem opcSalir;
    // End of variables declaration//GEN-END:variables

    
}
